version: '3.1'

services:
  adm_proyectos_pg:
    image: postgres:15.1
    container_name: adm_proyectos_pg
    restart: always
    environment:
      - POSTGRES_DB=admproyectosdb
      - POSTGRES_USER=matias
      - POSTGRES_PASSWORD=secret123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432